id: Humio-Test
version: -1
name: Humio-Test
starttaskid: '0'
tasks:
  '0':
    id: '0'
    taskid: eac2e711-643a-42f2-86e8-95cb284a8a1f
    type: start
    task:
      id: eac2e711-643a-42f2-86e8-95cb284a8a1f
      version: -1
      name: ''
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - '1'
    separatecontext: false
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  '1':
    id: '1'
    taskid: 5fc27167-369b-4ca7-8a6b-1742398f8541
    type: regular
    task:
      id: 5fc27167-369b-4ca7-8a6b-1742398f8541
      version: -1
      name: DeleteContext
      script: DeleteContext
      type: regular
      iscommand: true
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - '2'
    scriptarguments:
      all:
        simple: true
    separatecontext: false
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 200\n  }\n}"
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  '2':
    id: '2'
    taskid: d9242f37-9674-4761-835b-30e0ce0f1306
    type: regular
    task:
      id: d9242f37-9674-4761-835b-30e0ce0f1306
      version: -1
      name: humio-query
      script: '|||humio-query'
      type: regular
      iscommand: true
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - '3'
    scriptarguments:
      arguments: {}
      end: {}
      isLive: {}
      queryString:
        simple: foo=bar
      repository:
        simple: xsoar_e2e
      start: {}
      timeZoneOffsetMinutes: {}
    separatecontext: false
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 400\n  }\n}"
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  '3':
    id: '3'
    taskid: 5964fa09-620a-4c70-8193-ea69d0836299
    type: condition
    task:
      id: 5964fa09-620a-4c70-8193-ea69d0836299
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      true:
      - '4'
    separatecontext: false
    conditions:
    - label: true
      condition:
      - - operator: isExists
          left:
            value:
              simple: Humio.Query
            iscontext: true
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 600\n  }\n}"
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  '4':
    id: '4'
    taskid: 6e610e2b-ce38-496c-8363-9e3696b9b7e0
    type: regular
    task:
      id: 6e610e2b-ce38-496c-8363-9e3696b9b7e0
      version: -1
      name: humio-query-job
      script: '|||humio-query-job'
      type: regular
      iscommand: true
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - '6'
    scriptarguments:
      arguments: {}
      end: {}
      isLive: {}
      queryString:
        simple: foo=bar
      repository:
        simple: xsoar_e2e
      start: {}
      timeZoneOffsetMinutes: {}
    separatecontext: false
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 800\n  }\n}"
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  '6':
    id: '6'
    taskid: 950573d1-3403-4694-899f-7c0087803f9b
    type: regular
    task:
      id: 950573d1-3403-4694-899f-7c0087803f9b
      version: -1
      name: humio-poll
      script: '|||humio-poll'
      type: regular
      iscommand: true
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - '7'
    scriptarguments:
      id:
        simple: ${Humio.Job.id}
      repository:
        simple: xsoar_e2e
    separatecontext: false
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1040\n  }\n}"
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  '7':
    id: '7'
    taskid: bdb52d4c-4028-4735-80c9-c7e47c21f062
    type: condition
    task:
      id: bdb52d4c-4028-4735-80c9-c7e47c21f062
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      true:
      - '9'
    separatecontext: false
    conditions:
    - label: true
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: Humio.Result
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Humio.Result.cancelled
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: Humio.Result.events
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Humio.Result.done
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Humio.Result.metaData
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Humio.Result.job_id
            iscontext: true
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1310\n  }\n}"
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  '9':
    id: '9'
    taskid: 25870226-114a-4760-8731-4008002f9880
    type: regular
    task:
      id: 25870226-114a-4760-8731-4008002f9880
      version: -1
      name: humio-list-alerts
      script: '|||humio-list-alerts'
      type: regular
      iscommand: true
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - '10'
    scriptarguments:
      repository:
        simple: xsoar_e2e
    separatecontext: false
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1680\n  }\n}"
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  '10':
    id: '10'
    taskid: 7ba920e7-4117-4684-839e-aed20eff6c2c
    type: condition
    task:
      id: 7ba920e7-4117-4684-839e-aed20eff6c2c
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      true:
      - '11'
    separatecontext: false
    conditions:
    - label: true
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: Humio.Alert.description
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Humio.Alert.id
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Humio.Alert.name
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Humio.Alert.notifiers
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Humio.Alert.query.end
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Humio.Alert.query.isLive
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Humio.Alert.query.queryString
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Humio.Alert.query.start
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Humio.Alert.silenced
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Humio.Alert.throttleTimeMillis
            iscontext: true
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1970\n  }\n}"
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  '11':
    id: '11'
    taskid: 55868f75-feee-445e-88fa-4f6679300c09
    type: regular
    task:
      id: 55868f75-feee-445e-88fa-4f6679300c09
      version: -1
      name: humio-get-alert-by-id
      script: '|||humio-get-alert-by-id'
      type: regular
      iscommand: true
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - '12'
    scriptarguments:
      id:
        simple: ${Humio.Alert.id}
      repository:
        simple: xsoar_e2e
    separatecontext: false
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2200\n  }\n}"
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  '12':
    id: '12'
    taskid: 804a9bbc-4e85-425c-8ca8-8f1420743a33
    type: condition
    task:
      id: 804a9bbc-4e85-425c-8ca8-8f1420743a33
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      true:
      - '15'
    separatecontext: false
    conditions:
    - label: true
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: Humio.Alert.description
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Humio.Alert.id
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Humio.Alert.name
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Humio.Alert.notifiers
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Humio.Alert.query.end
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Humio.Alert.query.isLive
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Humio.Alert.query.queryString
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Humio.Alert.query.start
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Humio.Alert.silenced
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Humio.Alert.throttleTimeMillis
            iscontext: true
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2400\n  }\n}"
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  '15':
    id: '15'
    taskid: 83c13538-fbc4-4a5c-8e4f-447bc5b965cd
    type: regular
    task:
      id: 83c13538-fbc4-4a5c-8e4f-447bc5b965cd
      version: -1
      name: humio-list-notifiers
      script: '|||humio-list-notifiers'
      type: regular
      iscommand: true
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - '16'
    scriptarguments:
      repository:
        simple: xsoar_e2e
    separatecontext: false
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3000\n  }\n}"
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  '16':
    id: '16'
    taskid: 9669fca5-1e33-4299-8d93-3eae361043f3
    type: condition
    task:
      id: 9669fca5-1e33-4299-8d93-3eae361043f3
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      true:
      - '21'
    separatecontext: false
    conditions:
    - label: true
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: Humio.Notifier
            iscontext: true
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3200\n  }\n}"
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  '21':
    id: '21'
    taskid: ca0f349f-d6f6-41d2-87b3-3571e0171e93
    type: regular
    task:
      id: ca0f349f-d6f6-41d2-87b3-3571e0171e93
      version: -1
      name: humio-get-notifier-by-id
      script: '|||humio-get-notifier-by-id'
      type: regular
      iscommand: true
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - '22'
    scriptarguments:
      id:
        simple: ${Humio.Notifier.id}
      repository:
        simple: xsoar_e2e
    separatecontext: false
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 4030\n  }\n}"
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  '22':
    id: '22'
    taskid: 9ad4e1a1-ef17-4c1f-8452-81afbd0ce0ec
    type: condition
    task:
      id: 9ad4e1a1-ef17-4c1f-8452-81afbd0ce0ec
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      true:
      - '23'
    separatecontext: false
    conditions:
    - label: true
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: Humio.Notifier
            iscontext: true
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 4400\n  }\n}"
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  '23':
    id: '23'
    taskid: d4384346-e7fb-4101-88ee-531bcf8061fb
    type: title
    task:
      id: d4384346-e7fb-4101-88ee-531bcf8061fb
      version: -1
      name: Test Done
      type: title
      iscommand: false
      brand: ''
      description: ''
    separatecontext: false
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 4600\n  }\n}"
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 4615,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
inputs: []
outputs: []
fromversion: 5.0.0
description: ''
