id: GCPWhitelist_Feed_Test
version: 25
name: GCPWhitelist_Feed_Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 8880741e-ee8b-4fd8-877f-00a7058fa5ad
    type: start
    task:
      id: 8880741e-ee8b-4fd8-877f-00a7058fa5ad
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 460,
          "y": 60
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 914ea164-5046-41bc-830d-1ca16288da15
    type: regular
    task:
      id: 914ea164-5046-41bc-830d-1ca16288da15
      version: -1
      name: Get Indicators - GCP Whitelist (Limited)
      description: Gets indicators from the feed.
      script: GCP Whitelist Feed|||gcp-whitelist-get-indicators
      type: regular
      iscommand: true
      brand: GCP Whitelist Feed
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      extend-context:
        simple: Indicator=.
      limit:
        simple: "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 460,
          "y": 440
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: ea37c542-16dc-476c-8564-eaa9539c6d35
    type: condition
    task:
      id: ea37c542-16dc-476c-8564-eaa9539c6d35
      version: -1
      name: Assert Output
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "7"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: hasLength
          left:
            value:
              complex:
                root: Indicator
                accessor: raw_response
            iscontext: true
          right:
            value:
              simple: "2"
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: Indicator
                accessor: raw_response.[0].type
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: Indicator
                accessor: raw_response.[0].value
            iscontext: true
    view: |-
      {
        "position": {
          "x": 460,
          "y": 620
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 15698bb9-0e84-473a-880d-1bf28fd28317
    type: regular
    task:
      id: 15698bb9-0e84-473a-880d-1bf28fd28317
      version: -1
      name: Done
      description: commands.local.cmd.close.inv
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 460,
          "y": 1410
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: 83b68382-7653-413c-88e5-f8a61a085b8d
    type: regular
    task:
      id: 83b68382-7653-413c-88e5-f8a61a085b8d
      version: -1
      name: Get Indicators - GCP Whitelist (Default Limit)
      description: Gets indicators from the feed.
      script: GCP Whitelist Feed|||gcp-whitelist-get-indicators
      type: regular
      iscommand: true
      brand: GCP Whitelist Feed
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      extend-context:
        simple: Indicator=.
      limit: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 460,
          "y": 990
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: b873da32-f1f1-4353-8a9a-a230722397ee
    type: condition
    task:
      id: b873da32-f1f1-4353-8a9a-a230722397ee
      version: -1
      name: Assert Output
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: hasLength
          left:
            value:
              complex:
                root: Indicator
                accessor: raw_response
            iscontext: true
          right:
            value:
              simple: "10"
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: Indicator
                accessor: raw_response.[0].type
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: Indicator
                accessor: raw_response.[0].value
            iscontext: true
    view: |-
      {
        "position": {
          "x": 460,
          "y": 1190
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: 47a2dadc-adec-4aab-8c3a-eb68b9c19111
    type: regular
    task:
      id: 47a2dadc-adec-4aab-8c3a-eb68b9c19111
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 460,
          "y": 820
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: 844dfb5e-b7e2-4abf-8ea6-7f1d8a0a36e3
    type: regular
    task:
      id: 844dfb5e-b7e2-4abf-8ea6-7f1d8a0a36e3
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 460,
          "y": 245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1445,
        "width": 380,
        "x": 460,
        "y": 60
      }
    }
  }
inputs: []
outputs: []